# -*- coding: utf-8 -*-
"""كشف الوجه.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YyMLQQyKSlSiADFhdUIsv5bIPMdbS5sI
"""

import cv2
from google.colab.patches import cv2_imshow
#استيراد openCV لمعالجوة الصورة

# استخدام نص خام لتجنب الأخطاء
#قراءة الصورة
img = cv2.imread(r"/content/0_DaHYOit2CoXfGPJ7.jpg")

# لعرض الصورة في المكتبةopen cv
cv2_imshow(img)

model = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_frontalface_default.xml")
#تحميل نموذج كشف الوجوه

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
#تحويل الصورة الى اللون ال

# لعرض الصورة في المكتبةopen cv
cv2_imshow(gray)

#كشف الوجه في الصورة الرمادية
face =model.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5)

# طباعة عدد الوجوه المكتشفة
print(f"عدد الوجوه المكتشفة: {len(face)}")

# لوب لإيجاد الوجوه ورسم مستطيل علي الصورة الأصلية
for (x, y, w, h) in face:
    cv2.rectangle(img, (x, y), (x + w, y + h), (0, 237, 214), 2)

# عرض الصورة بعد كشف الوجوه
cv2_imshow(img)